[platformio]
default_envs = master_node

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps = 
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.3

[env:master_node]
build_flags = 
    -D MASTER_NODE=1
    -D NUM_WORKERS=1
    -D SLIP_BAUDRATE=921600
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
upload_port = COM25
monitor_port = COM25

[env:worker_node]
build_flags = 
    -D WORKER_NODE=1
    -D SLIP_BAUDRATE=921600
build_src_filter = +<*> -<main_master.cpp> -<mqtt_slip_bridge.cpp>
upload_port = COM23
monitor_port = COM23

[env:worker2_node]
build_flags = 
    -D WORKER_NODE=1
    -D SLIP_BAUDRATE=921600
build_src_filter = +<*> -<main_master.cpp> -<mqtt_slip_bridge.cpp>
upload_port = COM26
monitor_port = COM26
